### ISSUE TITLE
Guide Update Master Issue

### ISSUE THREAD

**Issue by kfechter** [kfechter/LegionY530Ubuntu#24]
- [x]  Remove Non-LTS Version Support from guide
- [x]  Add ukuu installation steps to guide (possibly install and open as part of script.
- [x] Add notes for realtek wifi laptops
- [x] Add step for disabling AER on kernel 4.20
- [x] Get new screenshots
- [x] Remove scripts to make the guide less automated and prone to error.

**Comment by kfechter** [comment]
Guide has been updated and 18.04.2 is live. Guide is ready for master
