### ISSUE TITLE
18.04.3 Guide Update Master Issue

### ISSUE THREAD

**Issue by kfechter** [kfechter/LegionY530Ubuntu#29]
18.04.3 HWE should bring any fixes from 19.04 into the LTS. This should allow me to remove several steps of the guide. 

- [x] Figure out what kernel 18.04.3 will have
- [x] Test The guide
- [x] New screenshots for GPU step, as GPU step appears to be different now. 
- [x] Branch master and add link from new master branch for 18.04.2 installs until 18.04.3 is out
- [x]  Remove unecessary steps
- [x] Split guide into seperate .md files for guide and additional stuff 
- [x] Add 19.04 compatibility to the guide as 18.04.3 isnt slated for release until august

**Comment by kfechter** [comment]
If 19.04/18.04.3 ship with 4.20.x, then all of the steps regarding ukuu and rmmod can be removed.

**Comment by kfechter** [comment]
Secureboot steps can be split out since it's no longer necessary

**Comment by kfechter** [comment]
Steps are now all going to be seperate so that its not a scrollfest.

**Comment by kfechter** [comment]
Pretty much certain 19.04 will ship with 4.20 at this point.

**Comment by kfechter** [comment]
It may ship with 5.x, which is good too.

**Comment by kfechter** [comment]
19.04/18.04 will ship with kernel 5.0

**Comment by kfechter** [comment]
18.04.3 is slated for release in August. since 19.04 is out first with the fixes, I have updated the guide to support installation of 19.04. The 18.04.2 guide is now a seperate branch, and will be deprecated when 18.04.3 is officially out.

**Comment by kfechter** [comment]
Tested in a VM, and tested the nvidia install bits on a live disk. Everything should be good and I can do cleanup of any lingering issues after i merge up to master
